In [3]:
#DSBDA Practical 1

#1. Import Required Libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

#2. Import or Load Dataset
df = pd.read_csv(r"C:\Users\Ritesh Bhosale\Downloads\Sem-6\practical\DSBDA Prac\1\SVMtrain.csv")
df.head()

,PassengerId,Survived,Pclass,Sex,Age,SibSp,Parch,Fare,Embarked
0,1,0,3,Male,22.0,1,0,7.2500,3
1,2,1,1,female,38.0,1,0,71.2833,1
2,3,1,3,female,26.0,0,0,7.9250,3
3,4,1,1,female,35.0,1,0,53.1000,3
4,5,0,3,Male,35.0,0,0,8.0500,3

In [4]:
#3.Data Preprocessing
print(df.isnull().sum())
print(df.describe())
print("Rows:", df.shape[0])
print("Columns:", df.shape[1])

PassengerId    0
Survived       0
Pclass         0
Sex            0
Age            0
SibSp          0
Parch          0
Fare           0
Embarked       0
dtype: int64
       PassengerId    Survived      Pclass         Age       SibSp  \
count   889.000000  889.000000  889.000000  889.000000  889.000000
mean    446.000000    0.382452    2.311586   35.686355    0.524184
std     256.998173    0.486260    0.834700   17.756733    1.103705
min       1.000000    0.000000    1.000000    0.420000    0.000000
25%     224.000000    0.000000    2.000000   22.000000    0.000000
50%     446.000000    0.000000    3.000000   32.000000    0.000000
75%     668.000000    1.000000    3.000000   54.000000    1.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000

            Parch        Fare    Embarked
count  889.000000  889.000000  889.000000
mean     0.382452   32.096681    2.535433
std      0.806761   49.697504    0.792088
min      0.000000    0.000000    1.000000
25%      0.000000    7.895800    2.000000
50%      0.000000   14.454200    3.000000
75%      0.000000   31.000000    3.000000
max      6.000000  512.329200    3.000000
Rows: 889
Columns: 9

In [5]:
#4. Data Formatting And Normalization
print(df.dtypes)
df['Survived'] = df['Survived'].astype('category')
df['Pclass'] = df['Pclass'].astype('category')
df['Sex'] = df['Sex'].astype('category')
df['Embarked']=df['Embarked'].astype('category')
print(df.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Sex             object
Age            float64
SibSp            int64
Parch            int64
Fare           float64
Embarked         int64
dtype: object
PassengerId       int64
Survived       category
Pclass         category
Sex            category
Age             float64
SibSp             int64
Parch             int64
Fare            float64
Embarked       category
dtype: object

In [6]:
#5. Turning Categorical Variables into Quantitative
df_encoded = pd.get_dummies(df, columns=['Sex', 'Embarked', 'Pclass'])
df_encoded.head()

,PassengerId,Survived,Age,SibSp,Parch,Fare,Sex_Male,Sex_female,Embarked_1,Embarked_2,Embarked_3,Pclass_1,Pclass_2,Pclass_3
0,1,0,22.0,1,0,7.2500,True,False,False,False,True,False,False,True
1,2,1,38.0,1,0,71.2833,False,True,True,False,False,True,False,False
2,3,1,26.0,0,0,7.9250,False,True,False,False,True,False,False,True
3,4,1,35.0,1,0,53.1000,False,True,False,False,True,True,False,False
4,5,0,35.0,0,0,8.0500,True,False,False,False,True,False,False,True